/**
 * Enrichment Pipeline — generates rich content (visualizations,
 * illustrations) when the router decides they're warranted.
 *
 * Visualizations are generated by the VISUALISER_AGENT (which has
 * the full component library, design philosophy, and interaction
 * guidance in its system prompt) and then refined through an
 * iterative critique→patch loop for factual accuracy.
 *
 * Separated from the orchestrator for single responsibility.
 */
import { ILLUSTRATOR_AGENT, VISUALISER_AGENT } from './agents';
import { runImageAgent, runTextAgent } from './run-agent';
import { EMBER_VIZ_KIT } from './viz-components';
import { refineArtifact } from './artifact-refiner';
import type { ChangeContract } from './artifact-refiner';
import type { NotebookEntry, LiveEntry } from '@/types/entries';

/** Generate an HTML visualization for a concept, with iterative refinement. */
export async function generateVisualization(
  prompt: string,
  entries: LiveEntry[],
  contract?: ChangeContract,
): Promise<NotebookEntry | null> {
  try {
    const recentContext = entries.slice(-5)
      .map((le) => 'content' in le.entry ? le.entry.content : '')
      .filter(Boolean)
      .join('\n');

    const vizPrompt = buildVisualizationPrompt(prompt, recentContext);
    const result = await runTextAgent(VISUALISER_AGENT, [{
      role: 'user',
      parts: [{ text: vizPrompt }],
    }]);

    let rawHtml = result.text;
    // Strip markdown fences if the model wrapped the response
    rawHtml = rawHtml.replace(/^```html\s*/i, '').replace(/```\s*$/i, '').trim();

    if (!rawHtml) return null;

    // Run critique→refine loop for factual accuracy
    const refined = await refineArtifact(rawHtml, prompt, recentContext, contract);

    const fullHtml = wrapHtml(refined.html);
    return {
      type: 'visualization',
      html: fullHtml,
      caption: `concept map: ${prompt.slice(0, 60)}`,
    };
  } catch {
    // Visualization failed — not critical
  }
  return null;
}

/** Generate a hand-drawn illustration for a concept. */
export async function generateIllustration(
  prompt: string,
): Promise<NotebookEntry | null> {
  try {
    const result = await runImageAgent(ILLUSTRATOR_AGENT, [{
      role: 'user',
      parts: [{
        text: `Draw a hand-sketched concept illustration for: ${prompt}. Style: warm sepia paper, fountain pen ink, minimal colour.`,
      }],
    }]);

    if (result.images.length > 0) {
      const img = result.images[0];
      if (img) {
        return {
          type: 'illustration',
          dataUrl: `data:${img.mimeType};base64,${img.data}`,
          caption: result.text || undefined,
        };
      }
    }
  } catch {
    // Illustration failed — not critical
  }
  return null;
}

function buildVisualizationPrompt(concept: string, context: string): string {
  const parts = [
    `Visualise this concept: ${concept}`,
    '',
    'Create a rich, interactive, multi-layered visualization.',
    'Use tabs for different perspectives, accordions for depth,',
    'timelines for sequences, grids of cards for taxonomies,',
    'and reveals for progressive disclosure.',
    'Combine components: carousel of comparisons, timeline with quotes, etc.',
    '',
    'Generate ONLY <body> content — CSS/JS are already injected.',
  ];
  if (context) {
    parts.push('', `Student's recent exploration:\n${context}`);
  }
  return parts.join('\n');
}

function wrapHtml(body: string): string {
  return [
    '<!DOCTYPE html><html><head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    EMBER_VIZ_KIT,
    '</head><body>',
    body,
    '</body></html>',
  ].join('');
}
