/**
 * Illustration — renders AI-generated concept sketches.
 * Hand-drawn feel on warm paper, generated by the Illustrator agent.
 * The tutor's quick sketch to make an idea visible.
 */
import styles from './Illustration.module.css';

interface IllustrationProps {
  dataUrl: string;
  caption?: string;
}

export function Illustration({ dataUrl, caption }: IllustrationProps) {
  return (
    <figure className={styles.figure}>
      <img
        className={styles.image}
        src={dataUrl}
        alt={caption ?? 'Concept illustration'}
        loading="lazy"
      />
      {caption && (
        <figcaption className={styles.caption}>{caption}</figcaption>
      )}
    </figure>
  );
}
