/**
 * Visualization — renders AI-generated HTML concept diagrams
 * inside a sandboxed iframe. The tutor's whiteboard.
 * Generated by the Visualiser agent using Ember's design tokens.
 */
import { useRef, useEffect, useState } from 'react';
import styles from './Visualization.module.css';

interface VisualizationProps {
  html: string;
  caption?: string;
}

export function Visualization({ html, caption }: VisualizationProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [height, setHeight] = useState(300);

  // Auto-resize iframe to content height
  useEffect(() => {
    const iframe = iframeRef.current;
    if (!iframe) return;

    const handleLoad = () => {
      try {
        const doc = iframe.contentDocument;
        if (doc?.body) {
          const h = doc.body.scrollHeight;
          setHeight(Math.min(Math.max(h, 200), 800));
        }
      } catch {
        // Cross-origin or sandbox restriction — use default
      }
    };

    iframe.addEventListener('load', handleLoad);
    return () => iframe.removeEventListener('load', handleLoad);
  }, [html]);

  return (
    <div className={styles.container}>
      <iframe
        ref={iframeRef}
        className={styles.frame}
        srcDoc={html}
        sandbox="allow-scripts"
        title={caption ?? 'Concept visualization'}
        style={{ height: `${height}px` }}
      />
      {caption && (
        <p className={styles.caption}>{caption}</p>
      )}
    </div>
  );
}
